{
  "formatVersion": "1.1",
  "component": {
    "group": "com.edger.plugin",
    "module": "lifecycle",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "vkf2bab7ure45kftcjix42tht4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "lifecycle-1.0.0.jar",
          "url": "lifecycle-1.0.0.jar",
          "size": 15548,
          "sha512": "74811a3eff48ca493a5023ed11195b851ddb8eb3dd51d6c7801c4d66fadd499ec0990a4e258fa7c5ee2b076d63cb4bf7cbc8909cf664b0ac48e1973825b46f43",
          "sha256": "ef6774c8f0bcf80e07ce5f01d7af1639089e5f1a84078b603a80f24e5b5ba088",
          "sha1": "f6986b7335a896b3669234f47150a3ab015d101e",
          "md5": "c2c27c3cba73d2e398fa2d05a26118d5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "4.1.3"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "7.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "7.1"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-1.0.0.jar",
          "url": "lifecycle-1.0.0.jar",
          "size": 15548,
          "sha512": "74811a3eff48ca493a5023ed11195b851ddb8eb3dd51d6c7801c4d66fadd499ec0990a4e258fa7c5ee2b076d63cb4bf7cbc8909cf664b0ac48e1973825b46f43",
          "sha256": "ef6774c8f0bcf80e07ce5f01d7af1639089e5f1a84078b603a80f24e5b5ba088",
          "sha1": "f6986b7335a896b3669234f47150a3ab015d101e",
          "md5": "c2c27c3cba73d2e398fa2d05a26118d5"
        }
      ]
    }
  ]
}
