{
  "formatVersion": "1.1",
  "component": {
    "group": "com.edger.plugin",
    "module": "lifecycle",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "t5od3lmlw5gsznsyfg2752smba"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "lifecycle-1.0.0.jar",
          "url": "lifecycle-1.0.0.jar",
          "size": 15833,
          "sha512": "fc07b2986ac3b85c7ef479c0a65bf39187402dd39d11d8a43cec77f6b80ee715403ab22f672da42facd1747eb660e70a2d4bb2c57d9807578ba0a8a612d8f5db",
          "sha256": "bbda3e9bf53fa2f9bb70dea04006e4f764fd59670e8283c497305496228a4b69",
          "sha1": "468e064e7fb5202b1e8a387143b8e3b408196d22",
          "md5": "a4858c0ac32f34950b50db8c338cb1c1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "4.1.3"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "7.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "7.1"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-1.0.0.jar",
          "url": "lifecycle-1.0.0.jar",
          "size": 15833,
          "sha512": "fc07b2986ac3b85c7ef479c0a65bf39187402dd39d11d8a43cec77f6b80ee715403ab22f672da42facd1747eb660e70a2d4bb2c57d9807578ba0a8a612d8f5db",
          "sha256": "bbda3e9bf53fa2f9bb70dea04006e4f764fd59670e8283c497305496228a4b69",
          "sha1": "468e064e7fb5202b1e8a387143b8e3b408196d22",
          "md5": "a4858c0ac32f34950b50db8c338cb1c1"
        }
      ]
    }
  ]
}
